services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:9000
    # --- ADICIONE AQUI ---
    env_file:
      - .env
    volumes:
      # Monta o código fonte para desenvolvimento dentro do container
      - .:/app
      # Volume persistente para o SQLite
      - sqlite_data:/app
      # Volume para arquivos de mídia (uploads)
      - media_volume:/app/media
    ports:
      - "9000:9000"