"""
Django settings for squat_analysis_app project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Diretório raiz dos relatórios Excel gerados pelo pipeline (planilhas/).
# Centralizado aqui para que o Service Layer, o Management Command de limpeza
# e o agendador em segundo plano usem exatamente o mesmo caminho absoluto.
PLANILHAS_ROOT_DIR = BASE_DIR / 'planilhas'

# Iniciando o environ
env = environ.Env(
    DEBUG=(bool, False)
)

# Lendo o arquivo .env
environ.Env.read_env(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# Pegando a secret_key do .env
SECRET_KEY = env('SECRET_KEY')
# Pegando o DEBUG do .env
DEBUG = env('DEBUG')
# Pegando os ALLOWED_HOSTS do .env
ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=[])


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'squat_analyzer',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'squat_analysis_app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'squat_analysis_app.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }   
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Configurações de arquivos de mídia (uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Configurações de arquivos estáticos
STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'squat_analyzer' / 'static']

# ------------------------------------------------------------------ #
# Otimizacao de Upload (docs/tasks/(2)OPTIMIZE.md - Fase 2)          #
# ------------------------------------------------------------------ #
# FILE_UPLOAD_MAX_MEMORY_SIZE baixo forcа o Django a gravar uploads
# que excedem 1 MB diretamente em TemporaryUploadedFile (disco), em vez
# de reter videos MP4 inteiros na RAM do worker (InMemoryUploadedFile).
FILE_UPLOAD_MAX_MEMORY_SIZE = 1048576   # 1 MB -> streaming para disco
DATA_UPLOAD_MAX_MEMORY_SIZE = 104857600 # ~100MB -> teto de payload (validado por MP4VideoValidator)

# Handlers explicitos: o MemoryFileUploadHandler pequeno transfere o resto
# para TemporaryFileUploadHandler, que faz o streaming direto para o disco
# temporario do servidor sem buffer completo em memoria.
FILE_UPLOAD_HANDLERS = [
    'django.core.files.uploadhandler.MemoryFileUploadHandler',
    'django.core.files.uploadhandler.TemporaryFileUploadHandler',
]

# Ajustes quando estiver em produção com HTTPS
# Redireciona todas as requisições HTTP para HTTPS
SECURE_SSL_REDIRECT = env.bool('SECURE_SSL_REDIRECT', default=False)

# Cookies seguros apenas via HTTPS
SESSION_COOKIE_SECURE = env.bool('SESSION_COOKIE_SECURE', default=True)
CSRF_COOKIE_SECURE = env.bool('CSRF_COOKIE_SECURE', default=True)

# HSTS (HTTP Strict Transport Security)
# Define por quanto tempo o navegador deve lembrar que o site só pode ser acessado via HTTPS
SECURE_HSTS_SECONDS = env.int('SECURE_HSTS_SECONDS', default=31536000)  # 1 ano
SECURE_HSTS_INCLUDE_SUBDOMAINS = env.bool('SECURE_HSTS_INCLUDE_SUBDOMAINS', default=True)
SECURE_HSTS_PRELOAD = env.bool('SECURE_HSTS_PRELOAD', default=True)

# Protege contra clickjacking
X_FRAME_OPTIONS = 'DENY'

# Protege contra MIME type sniffing
SECURE_CONTENT_TYPE_NOSNIFF = True

# Filtra conteúdo XSS em navegadores mais antigos
SECURE_BROWSER_XSS_FILTER = True

# Referrer Policy
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'

# ------------------------------------------------------------------ #
# Logging estruturado (Fase 3 - tarefa 3.2)                          #
# Auditoria da rotina de limpeza autonoma de planilhas: registra o    #
# nome do arquivo deletado, caminho completo e timestamp da exclusao. #
# ------------------------------------------------------------------ #
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'structured': {
            'format': '[{asctime}] [{levelname}] {name}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'structured',
        },
    },
    'loggers': {
        # Logger dedicado à camada de serviço/agendador de limpeza de planilhas
        'squat_analyzer.services.cleanup_service': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'squat_analyzer.management.commands.cleanup_oldest_sheet': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
